### ISSUE TITLE
autofollow most requested users

### ISSUE THREAD

**Issue by Tschaul** [digital-dreamer/twister-proxy#7]
Hi,

At https://github.com/Tschaul/LibTwister i'm building an javascript library that works together with this proxy to enable access to the twister network (right now its read only and incomplete). When i query my own timeline of the last 24h over this it takes up to 1min until all the information is pulled down (including avatar and profiles, proxy sitting in a data center). While this is much better than starting up twisterd locally, which takes multiple minutes until it joined all the swarms, 1min boot-up-time is far from perfect. 

Partly this can be optimized on the client side. But the best improvement i think would be if the proxy would keep statistics on which users posts are request most often and let twisterd join those swarms ("follow" as "guest"). The client could then check through the "torrentstatus" method whether the proxy has joined a given swarm and then use "getposts" to query posts. 

Right now these methods ("follow", "torrentstatus" and "getposts") are not available in public-server-mode. So they would have to be opened up. But i don't really know what the public-server-mode is good for because twister-proxy is already limiting the API-access and twisterd only accepts calls from localhost (if set so).

What do you think? I will play around a bit and let u know then.

**Comment by digital-dreamer** [comment]
I see, there is a misunderstanding about public_server_mode - you don't have to use this flag. Let me explain how the idea started. A year ago, some users requested a feature to run read-only servers, and I implemented it in twister-core, but Miguel noticed that DDoS attack would still be possible, this was the original reason why I wrote twister-proxy.

If you use client-side crypto, the servers don't have to be strictly read-only. You don't have to run twisterd with the public_server_mode flag, instead just connect twister-proxy to it and set the limits and filters in its settings.json file.

I learned about what you want to use it for, and so I made an adjustment to make it easier, I moved the forbidden call settings to the json file. All API functions are now listed. CallsPerMinute==0 means completely forbidden, a positive number means allowed but limited rate, Null means no limit. I pushed it 3 days ago, so if you can pull the latest version from this repo, you don't have to use the public_server_mode flag, and you can set your own rules in the proxy settings.

The predictive following is one option, an alternative would be to allow real torrent calls, and make the server join user's swarms when he logs in, and then leave them when user logs out or stops using the server for a set period of time. Which solution would be better?

**Comment by Tschaul** [comment]
Nice! I missed that change ;-)

If the server joins the swarms upon login, the boot-up time would again be minutes. The server would have to stay in the torrents so that everything is up to date when the client comes online. I'm guessing that staying in the torrent instead of leaving and rejoining doesn't make a big difference in terms of network resources. The posts have to be distributed at some point. Also, post distribution through torrents is more efficient than through the dht, so there is no reason the server shouldn't join a torrent as it saves resources.

So yes, the easiest way is probably to simply open up the follow and getposts methods. And then the problem is more about automatically leaving torrents rather than joining. Is there a way to query a complete list of active torrents from twisterd?

**Comment by digital-dreamer** [comment]
The only way I can think of is to call getfollowing for each active user and merge the results.

**Comment by centaur1** [comment]
Just to point out (assuming I am correctly understanding the above) that if you are using twister-proxy you should not need to use " -public_server_mode=1".  So on the twister-proxy document page, it does not need to be:
./twisterd -daemon -rpcallowip=127.0.0.1 -public_server_mode=1
but:
./twisterd -daemon -rpcallowip=127.0.0.1

Is that accurate?
